apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:scottseotech/todo-platform.git
    path: deploy/infrastructure/cnpg
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true