apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: todo-api
          image: todo-api
          env:
            - name: DB_HOST
              value: todo-db-rw.cnpg.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: DB_PASSWORD
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "tempo.observability.svc.cluster.local:4317"
            - name: ENVIRONMENT
              value: "production"
            - name: SERVICE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10 
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"

