schedule: "*/15 * * * *"

env:
  - SLACK_BOT_TOKEN
  - LOKI_URL

steps:
  - name: "error-15-minutes"
    description: "Checking for errors in the last 15 minutes..."
    command: "bash"
    script: |
      #!/bin/bash -xe

      todops version

      todops loki search error --since "15 minutes ago" | logmine -dhp | tr '\n' '\0' | xargs -0 -n1 -I{} todops slack post-message alerts --code "{}"