schedule: "*/15 * * * *"

env:
  LOKI_URL: "${LOKI_URL}"
  SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"

steps:
  - name: "error-15-minutes"
    description: "Checking for errors in the last 15 minutes..."
    shell: bash
    script: |
      #!/bin/bash

      todops loki search error -l 500 | logmine -dhp | tr '\n' '\0' | xargs -0 -n1 -I{} todops slack post-message alerts --code "{}"