apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: ssh-config
              mountPath: /home/argocd/.ssh/config
              subPath: config
              readOnly: true
      volumes:
        - name: ssh-config
          secret:
            secretName: argocd-ssh-config
