apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mcp 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: todo-mcp
          image: todo-mcp
          env:
            - name: TODO_API_URL
              value: todo-api.default.svc.cluster.local
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10 
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "256Mi"

