apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mcp 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: todo-mcp
          image: todo-mcp
          env:
            - name: TODO_API_URL
              value: todo-api.default.svc.cluster.local
            - name: TODO_MCP_URL
              value: todo-mcp.default.svc.cluster.local
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "tempo.observability.svc.cluster.local:4317"
            - name: ENVIRONMENT
              value: "production"
            - name: SERVICE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10 
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "256Mi"

