apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mcp 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: todo-mcp
          image: todo-mcp
          env:
            - name: DB_HOST
              value: todo-db-rw.cnpg.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: todo-mcp-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-mcp-secret
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10 
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"

