apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/applications/docs
    repoURL: git@github.com:scottseotech/todo-platform.git
    targetRevision: main 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true