name: Homer Image Build

on:
  push:
    branches:
      - "main"
    paths:
      - "infra/homer/**"

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  IMG_NAME: curiosinauts/scottseotech-homer
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  # notify-start:
  #   uses: ./.github/workflows/notify-slack.yaml
  #   with:
  #     status: 'starting'
  #     workflow_name: 'Homer Image Build'
  #     message: 'Starting Homer Docker image build and deployment'
  #     branch: ${{ github.ref_name }}
  #     actor: ${{ github.actor }}
  #     channel: '#builds'
  #   secrets: inherit

  build:
    # needs: notify-start
    runs-on: self-hosted
    outputs:
      image_version: ${{ steps.metadata.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: infra/homer
          push: true
          # push: ${{ github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.') }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  call-argocd-update:
    needs: build
    uses: scottseotech/todo-platform/.github/workflows/argocd-update.yaml@main
    with:
      app_path: deploy/infrastructure/homer
      app: homer
      version: ${{ needs.build.outputs.image_version }}
    secrets: inherit

  # notify-success:
  #   needs: [build, call-argocd-update]
  #   if: success()
  #   uses: ./.github/workflows/notify-slack.yaml
  #   with:
  #     status: 'success'
  #     workflow_name: 'Homer Image Build'
  #     message: 'Homer build and deployment completed successfully!'
  #     branch: ${{ github.ref_name }}
  #     actor: ${{ github.actor }}
  #     channel: '#builds'
  #   secrets: inherit

  # notify-failure:
  #   needs: [build, call-argocd-update]
  #   if: failure()
  #   uses: ./.github/workflows/notify-slack.yaml
  #   with:
  #     status: 'failure'
  #     workflow_name: 'Homer Image Build'
  #     message: 'Homer build pipeline failed - check logs for details'
  #     branch: ${{ github.ref_name }}
  #     actor: ${{ github.actor }}
  #     channel: '#builds'
  #   secrets: inherit