name: Todo Bot Image Build

on:
  push:
    branches:
      - "main"
    paths:
      - "services/todo-bot/**"

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  IMG_NAME: curiosinauts/scottseotech-todo-bot
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

run-name: "Todo Bot Image Build - ${{ github.run_id }}"

jobs:
  start:
    uses: ./.github/workflows/slack-notification.yaml
    with:
      status: 'starting'
      workflow_name: 'Todo Bot Image Build'
      message: 'Starting build and deployment'
      branch: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      channel: '#builds'
    secrets: inherit

  build:
    needs: start
    runs-on: self-hosted
    outputs:
      image_version: ${{ steps.metadata.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: services/todo-bot
          build-args: |
            BUILDKIT_PROGRESS=plain
          push: true
          # push: ${{ github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.') }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  call:
    needs: build
    uses: scottseotech/todo-platform/.github/workflows/argocd-update.yaml@main
    with:
      namespace: default
      app_path: deploy/applications
      app: todo-bot
      version: ${{ needs.build.outputs.image_version }}
    secrets: inherit

  success:
    needs: [build, call]
    if: success()
    uses: ./.github/workflows/slack-notification.yaml
    with:
      status: 'success'
      workflow_name: 'Todo Bot Image Build'
      message: 'Build and deployment completed'
      branch: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      channel: '#builds'
    secrets: inherit

  failure:
    needs: [build, call]
    if: failure()
    uses: ./.github/workflows/slack-notification.yaml
    with:
      status: 'failure'
      workflow_name: 'Todo Bot Image Build'
      message: 'Build pipeline failed - check logs for details'
      branch: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      channel: '#builds'
    secrets: inherit